services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - "8096:8096"
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - type: bind
        source: ${MOVIES_PATH}
        target: /media/movies
      - type: bind
        source: ${SHOWS_PATH}
        target: /media/shows
    restart: "unless-stopped"
    environment:
      - JELLYFIN_PublishedServerUrl=http://${DOMAIN}
    extra_hosts:
      - "host.docker.internal:host-gateway"
  caddy:
    image: caddy-porkbun:latest
    build: .
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    env_file: ./caddy/.env
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config

volumes:
  jellyfin-config:
    external: true
  jellyfin-cache:
    external: true
  caddy-data:
    external: true
  caddy-config:
    external: true
